#!/bin/bash
set -x
set -e

function repl {
  clj -A:dev -e "(init)" -r
}

function fig {
  clj -A:dev -m figwheel.main -b dev -r
}

function serve {
  python -m http.server -d target/dev
}

function push {
  clj -e "(do (doto 'bud.client.static require in-ns) (gensite \"target/prod\"))"
  clj -m cljs.main -co prod.cljs.edn -c bud.client.core
  firebase deploy
}

"$@"
