#!/bin/bash
set -x
set -e

function repl {
  clj -A:dev -e "(do (nrepl) (gensite))" -r
}

function fig {
  clj -A:dev -m figwheel.main -b dev -r
}

function serve {
  (sleep 0.5; firefox dev.impl.sh:8000) &
  python -m http.server -d target/dev
}

function push {
  clj -e "(do (doto 'bud.client.static require in-ns) (gensite \"target/prod\"))"
  clj -m cljs.main -co prod.cljs.edn -c bud.client.core
  firebase deploy
}

cmd="$1"
shift
$cmd "$@"
