#!/bin/bash
set -x
set -e
export PATH=../bin/:$PATH

function repl {
  export DATOMIC_ENV_MAP="$(cat env.edn)"
  clj -A:dev:local -e "(do (nrepl) (go))" -r
}

function proxy {
  datomic-socks-proxy bud
}

function cleanup-git {
  rm -rf .git
}

function deploy {
  if ! (git status | grep -q "nothing to commit"); then
    echo Must deploy with a clean commit.
  fi
  uname=$(git rev-parse HEAD)
  files="$(git ls-files)"
  git init
  trap cleanup-git INT
  git add $files
  git commit -m $uname
  iondeploy $uname
}

"$@"
