#!/bin/bash
set -x
set -e

function repl {
  clj -A:dev -e "(do (nrepl) (go))" -r
}

function push {
  clojure -A:dev -m datomic.ion.dev "{:op :push :uname \"$(uuidgen)\"}"
}

function proxy {
  datomic-socks-proxy bud
}

cmd="$1"
shift
$cmd "$@"
