#!/bin/bash
set -x
set -e

function repl {
  export DATOMIC_ENV_MAP="$(cat env.edn)"
  clj -A:dev -A:local -e "(do (nrepl) (go))" -r
}

function push {
  clojure -A:dev -m datomic.ion.dev "{:op :push :uname \"$(uuidgen)\"}"
  #clojure -A:dev -m datomic.ion.dev "{:op :push}"
}

function proxy {
  datomic-socks-proxy bud
}

function deploy {
  ./deploy
}

cmd="$1"
shift
$cmd "$@"
